// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

/// @title IVerifier
/// @notice Interface for Groth16 proof verifiers generated by snarkjs
interface IVerifier {
    /// @notice Verifies a Groth16 proof
    /// @param proof The proof data (8 uint256 values: a[2], b[2][2], c[2])
    /// @param pubSignals The public signals array
    /// @return True if the proof is valid
    function verifyProof(
        uint256[8] calldata proof,
        uint256[] calldata pubSignals
    ) external view returns (bool);
}

/// @title ISellVerifier
/// @notice Interface for the sell circuit verifier
/// @dev Public signals: [merkleRoot, nullifierHash, tokenAmount, minEthOut, recipient, relayer, fee, changeCommitment, publicInputsBinding]
interface ISellVerifier {
    function verifyProof(
        uint256[8] calldata proof,
        uint256[9] calldata pubSignals
    ) external view returns (bool);
}

/// @title ITransferVerifier
/// @notice Interface for the transfer circuit verifier
/// @dev Public signals: [merkleRoot, nullifierHash, recipientCommitment, changeCommitment]
interface ITransferVerifier {
    function verifyProof(
        uint256[8] calldata proof,
        uint256[4] calldata pubSignals
    ) external view returns (bool);
}

/// @title IWithdrawVerifier
/// @notice Interface for the withdraw circuit verifier (exit privacy pool to public wallet)
/// @dev Public signals: [merkleRoot, nullifierHash, amount, recipient, recipientBinding]
interface IWithdrawVerifier {
    function verifyProof(
        uint256[8] calldata proof,
        uint256[5] calldata pubSignals
    ) external view returns (bool);
}

/// @title IVoteVerifier
/// @notice Interface for the private voting circuit verifier
/// @dev Public signals: [proposalId, merkleRoot, nullifierHash, voteWeight, support, voteBinding]
interface IVoteVerifier {
    function verifyProof(
        uint256[8] calldata proof,
        uint256[6] calldata pubSignals
    ) external view returns (bool);
}

/// @title ISwapVerifier
/// @notice Interface for the $R00T <-> Project token swap circuit verifier
/// @dev Public signals: [inputMerkleRoot, inputNullifierHash, inputAmount, outputCommitment, minOutputAmount, changeCommitment, publicInputsBinding]
interface ISwapVerifier {
    function verifyProof(
        uint256[8] calldata proof,
        uint256[7] calldata pubSignals
    ) external view returns (bool);
}

/// @title IAddLiquidityVerifier
/// @notice Interface for add liquidity circuit verifier (dual-sided LP)
/// @dev Public signals: [merkleRoot, nullifierHash, tokenAmount, lpCommitment, changeCommitment, publicInputsBinding]
interface IAddLiquidityVerifier {
    function verifyProof(
        uint256[8] calldata proof,
        uint256[6] calldata pubSignals
    ) external view returns (bool);
}

/// @title IRemoveLiquidityVerifier
/// @notice Interface for remove liquidity circuit verifier (ETH/R00T main pool)
/// @dev Public signals: [publicInputsBinding, lpMerkleRoot, nullifierHash, commitment, lpShares, minEthOut, recipient, changeCommitment, tokenCommitment, tokensOut]
/// SECURITY FIX: Added commitment to pubSignals to bind proof to specific LP position
/// SECURITY FIX: Added tokenCommitment and tokensOut to verify token commitment contains correct amount
interface IRemoveLiquidityVerifier {
    function verifyProof(
        uint256[8] calldata proof,
        uint256[10] calldata pubSignals
    ) external view returns (bool);
}

/// @title IProjectPoolLPVerifier
/// @notice Interface for project pool LP withdrawal circuit verifier (R00T/token pairs)
/// @dev Public signals: [lpMerkleRoot, nullifierHash, commitment, lpShares, r00tOutputCommitment, tokenOutputCommitment, minR00tOut, publicInputsBinding]
/// NOTE: This is a separate circuit from IRemoveLiquidityVerifier (used for ETH/R00T pairs)
interface IProjectPoolLPVerifier {
    function verifyProof(
        uint256[8] calldata proof,
        uint256[8] calldata pubSignals
    ) external view returns (bool);
}

/// @title IClaimLPFeesVerifier
/// @notice Interface for LP fee claiming circuit verifier (SECURED VERSION)
/// @dev Public signals: [lpMerkleRoot, claimNullifier, feeEpoch, lpShares, recipient, publicInputsBinding]
/// SECURITY FIX: Uses epoch-based claim nullifiers to prevent unlimited fee claims
/// - claimNullifier = Poseidon(nullifier, feeEpoch, leafIndex)
/// - Each LP position can only claim once per epoch
/// - feeEpoch increments when fee distribution happens
interface IClaimLPFeesVerifier {
    function verifyProof(
        uint256[8] calldata proof,
        uint256[6] calldata pubSignals
    ) external view returns (bool);
}

/// @title IPledgeVerifier
/// @notice Interface for the PHASE C anonymous-pledge circuit verifier
/// @dev Proves ownership+spend of a shielded R00T note and mints a parcel-/value-bound
///      pledge commitment for later claim. Snarkjs emits circuit OUTPUTS first.
/// Public signals: [pledgeCommitment, publicInputsBinding, merkleRoot, nullifierHash, pledgeAmount, parcelId, creator]
/// - pledgeCommitment:    Poseidon(pledgeNullifier, pledgeSecret, parcelId, pledgeAmount) — inserted into the pledge tree
/// - publicInputsBinding: Poseidon(merkleRoot, nullifierHash, pledgeAmount, parcelId, creator)
/// - merkleRoot:          zkAMM R00T commitment-tree root (source of funds)
/// - nullifierHash:       spend nullifier for the R00T note (SHARED NullifierRegistry)
/// - pledgeAmount:        R00T pledged; 100% to land treasury AND exactly claimable later
/// - parcelId:            parcel being funded (bytes32 as field element)
/// - creator:             msg.sender of the pledge tx (funder binding; unlinked from claim wallet)
interface IPledgeVerifier {
    function verifyProof(
        uint256[8] calldata proof,
        uint256[7] calldata pubSignals
    ) external view returns (bool);
}

/// @title IClaimVerifier
/// @notice Interface for the PHASE C anonymous-claim circuit verifier
/// @dev Withdraw-shaped proof against the pledge tree, opening the 4-input parcel-bound
///      commitment so the contract mints EXACTLY `amount` of EXACTLY `parcelId`'s token
///      to `recipient`. Over-claim / cross-parcel claim are cryptographically impossible.
/// Public signals: [recipientBinding, merkleRoot, nullifierHash, parcelId, amount, recipient]
/// - recipientBinding: Poseidon(parcelId, amount, recipient) — anti-front-run binding
/// - merkleRoot:       pledge-tree root
/// - nullifierHash:    claim nullifier (SHARED NullifierRegistry) — blocks double-claim
/// - parcelId:         parcel whose token is minted (must match the commitment)
/// - amount:           parcel tokens minted == pledged amount (bound in the commitment)
/// - recipient:        wallet receiving the minted parcel tokens (any wallet)
interface IClaimVerifier {
    function verifyProof(
        uint256[8] calldata proof,
        uint256[6] calldata pubSignals
    ) external view returns (bool);
}

/// @title IDepositVerifier
/// @notice Interface for the deposit-binding circuit verifier (CRITICAL-1 fix)
/// @dev Proves a note's public `amount` equals the amount baked into its public
///      `commitment` (commitment == Poseidon(nullifier, secret, amount)). The zkAMM
///      verifies this before inserting a commitment so a note's value can never
///      exceed the R00T actually deposited / the curve's tokensOut.
/// Public signals: [binding, amount, commitment]  (Circom output first)
/// - binding:    Poseidon(amount, commitment) — anti-malleability binding output
/// - amount:     R00T deposited (contract-enforced == transferred / tokensOut)
/// - commitment: the note being inserted into the merkle tree
interface IDepositVerifier {
    function verifyProof(
        uint256[8] calldata proof,
        uint256[3] calldata pubSignals
    ) external view returns (bool);
}

/// @notice LandVault fund binding — commitment binds (parcelId, amount).
/// @dev Public signals: [binding, parcelId, amount, commitment] (Circom output first).
interface ILandDepositVerifier {
    function verifyProof(
        uint256[8] calldata proof,
        uint256[4] calldata pubSignals
    ) external view returns (bool);
}

/// @title IMergeVerifier
/// @notice Interface for privacy-preserving commitment consolidation circuit verifier
/// @dev Proves ownership of 2 commitments and merges them into a single output commitment
/// Public signals: [merkleRoot, nullifierHash1, nullifierHash2, outputCommitment, publicInputsBinding]
/// SECURITY FEATURES:
/// - Both inputs verified via merkle proof (same root)
/// - Distinct nullifier hashes prevent double-spending each input
/// - Output commitment contains sum of input amounts
/// - publicInputsBinding prevents proof malleability
interface IMergeVerifier {
    function verifyProof(
        uint256[8] calldata proof,
        uint256[5] calldata pubSignals
    ) external view returns (bool);
}
