// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

/// @title IVerifier
/// @notice Interface for Groth16 proof verifiers generated by snarkjs
interface IVerifier {
    /// @notice Verifies a Groth16 proof
    /// @param proof The proof data (8 uint256 values: a[2], b[2][2], c[2])
    /// @param pubSignals The public signals array
    /// @return True if the proof is valid
    function verifyProof(
        uint256[8] calldata proof,
        uint256[] calldata pubSignals
    ) external view returns (bool);
}

/// @title ISellVerifier
/// @notice Interface for the sell circuit verifier
/// @dev Public signals: [merkleRoot, nullifierHash, tokenAmount, minEthOut, recipient, relayer, fee, changeCommitment, publicInputsBinding]
interface ISellVerifier {
    function verifyProof(
        uint256[8] calldata proof,
        uint256[9] calldata pubSignals
    ) external view returns (bool);
}

/// @title ITransferVerifier
/// @notice Interface for the transfer circuit verifier
/// @dev Public signals: [merkleRoot, nullifierHash, recipientCommitment, changeCommitment]
interface ITransferVerifier {
    function verifyProof(
        uint256[8] calldata proof,
        uint256[4] calldata pubSignals
    ) external view returns (bool);
}

/// @title IWithdrawVerifier
/// @notice Interface for the withdraw circuit verifier (exit privacy pool to public wallet)
/// @dev Public signals: [merkleRoot, nullifierHash, amount, recipient, recipientBinding]
interface IWithdrawVerifier {
    function verifyProof(
        uint256[8] calldata proof,
        uint256[5] calldata pubSignals
    ) external view returns (bool);
}

/// @title IVoteVerifier
/// @notice Interface for the private voting circuit verifier
/// @dev Public signals: [proposalId, merkleRoot, nullifierHash, voteWeight, support, voteBinding]
interface IVoteVerifier {
    function verifyProof(
        uint256[8] calldata proof,
        uint256[6] calldata pubSignals
    ) external view returns (bool);
}

/// @title ISwapVerifier
/// @notice Interface for the $R00T <-> Project token swap circuit verifier
/// @dev Public signals: [inputMerkleRoot, inputNullifierHash, inputAmount, outputCommitment, minOutputAmount, changeCommitment, publicInputsBinding]
interface ISwapVerifier {
    function verifyProof(
        uint256[8] calldata proof,
        uint256[7] calldata pubSignals
    ) external view returns (bool);
}

/// @title IAddLiquidityVerifier
/// @notice Interface for add liquidity circuit verifier (dual-sided LP)
/// @dev Public signals: [merkleRoot, nullifierHash, tokenAmount, lpCommitment, changeCommitment, publicInputsBinding]
interface IAddLiquidityVerifier {
    function verifyProof(
        uint256[8] calldata proof,
        uint256[6] calldata pubSignals
    ) external view returns (bool);
}

/// @title IRemoveLiquidityVerifier
/// @notice Interface for remove liquidity circuit verifier (ETH/R00T main pool)
/// @dev Public signals: [publicInputsBinding, lpMerkleRoot, nullifierHash, commitment, lpShares, minEthOut, recipient, changeCommitment, tokenCommitment, tokensOut]
/// SECURITY FIX: Added commitment to pubSignals to bind proof to specific LP position
/// SECURITY FIX: Added tokenCommitment and tokensOut to verify token commitment contains correct amount
interface IRemoveLiquidityVerifier {
    function verifyProof(
        uint256[8] calldata proof,
        uint256[10] calldata pubSignals
    ) external view returns (bool);
}

/// @title IProjectPoolLPVerifier
/// @notice Interface for project pool LP withdrawal circuit verifier (R00T/token pairs)
/// @dev Public signals: [lpMerkleRoot, nullifierHash, commitment, lpShares, r00tOutputCommitment, tokenOutputCommitment, minR00tOut, publicInputsBinding]
/// NOTE: This is a separate circuit from IRemoveLiquidityVerifier (used for ETH/R00T pairs)
interface IProjectPoolLPVerifier {
    function verifyProof(
        uint256[8] calldata proof,
        uint256[8] calldata pubSignals
    ) external view returns (bool);
}

/// @title IClaimLPFeesVerifier
/// @notice Interface for LP fee claiming circuit verifier (SECURED VERSION)
/// @dev Public signals: [lpMerkleRoot, claimNullifier, feeEpoch, lpShares, recipient, publicInputsBinding]
/// SECURITY FIX: Uses epoch-based claim nullifiers to prevent unlimited fee claims
/// - claimNullifier = Poseidon(nullifier, feeEpoch, leafIndex)
/// - Each LP position can only claim once per epoch
/// - feeEpoch increments when fee distribution happens
interface IClaimLPFeesVerifier {
    function verifyProof(
        uint256[8] calldata proof,
        uint256[6] calldata pubSignals
    ) external view returns (bool);
}

/// @title IPledgeVerifier
/// @notice Interface for proposal pledge circuit verifier
/// @dev Proves ownership of ROOT commitment and locks it as pledge for proposal creation
/// Public signals: [merkleRoot, nullifierHash, pledgeAmount, creator, publicInputsBinding]
/// - merkleRoot: ROOT pool merkle root
/// - nullifierHash: Prevents double-spending the pledged ROOT
/// - pledgeAmount: Amount of ROOT being pledged
/// - creator: Address creating the proposal (binds proof to msg.sender)
/// - publicInputsBinding: Circuit binding to prevent proof reuse
interface IPledgeVerifier {
    function verifyProof(
        uint256[8] calldata proof,
        uint256[5] calldata pubSignals
    ) external view returns (bool);
}

/// @title IMergeVerifier
/// @notice Interface for privacy-preserving commitment consolidation circuit verifier
/// @dev Proves ownership of 2 commitments and merges them into a single output commitment
/// Public signals: [merkleRoot, nullifierHash1, nullifierHash2, outputCommitment, publicInputsBinding]
/// SECURITY FEATURES:
/// - Both inputs verified via merkle proof (same root)
/// - Distinct nullifier hashes prevent double-spending each input
/// - Output commitment contains sum of input amounts
/// - publicInputsBinding prevents proof malleability
interface IMergeVerifier {
    function verifyProof(
        uint256[8] calldata proof,
        uint256[5] calldata pubSignals
    ) external view returns (bool);
}
