// WorldIDGatekeeper ABI — W8: World ID Verification callback contract
export const WorldIDGatekeeperABI = [
  {
    type: "function",
    name: "requestVerification",
    inputs: [
      { name: "nullifierHash", type: "bytes32" },
      { name: "merkleRoot", type: "bytes32" },
      { name: "proof", type: "uint256[8]" },
      { name: "verificationLevel", type: "string" },
    ],
    outputs: [{ name: "requestId", type: "uint256" }],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "receiveVerificationResult",
    inputs: [
      { name: "requestId", type: "uint256" },
      { name: "verified", type: "bool" },
      { name: "reason", type: "string" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "isVerified",
    inputs: [{ name: "user", type: "address" }],
    outputs: [{ type: "bool" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getRequest",
    inputs: [{ name: "requestId", type: "uint256" }],
    outputs: [
      { name: "requester", type: "address" },
      { name: "nullifierHash", type: "bytes32" },
      { name: "status", type: "uint8" },
      { name: "verificationLevel", type: "string" },
      { name: "requestedAt", type: "uint256" },
      { name: "verifiedAt", type: "uint256" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getRequestStatus",
    inputs: [{ name: "requestId", type: "uint256" }],
    outputs: [{ type: "uint8" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "nextRequestId",
    inputs: [],
    outputs: [{ type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "verifiedHumans",
    inputs: [{ name: "user", type: "address" }],
    outputs: [{ type: "bool" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "usedNullifiers",
    inputs: [{ name: "nullifierHash", type: "bytes32" }],
    outputs: [{ type: "bool" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "totalVerified",
    inputs: [],
    outputs: [{ type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "totalPending",
    inputs: [],
    outputs: [{ type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "appId",
    inputs: [],
    outputs: [{ type: "string" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getVerificationData",
    inputs: [{ name: "requestId", type: "uint256" }],
    outputs: [
      { name: "nullifierHash", type: "bytes32" },
      { name: "merkleRoot", type: "bytes32" },
      { name: "proof", type: "uint256[8]" },
      { name: "verificationLevel", type: "string" },
    ],
    stateMutability: "view",
  },
  {
    type: "event",
    name: "VerificationRequested",
    inputs: [
      { name: "requestId", type: "uint256", indexed: true },
      { name: "requester", type: "address", indexed: true },
      { name: "nullifierHash", type: "bytes32", indexed: false },
      { name: "verificationLevel", type: "string", indexed: false },
    ],
  },
  {
    type: "event",
    name: "VerificationCompleted",
    inputs: [
      { name: "requestId", type: "uint256", indexed: true },
      { name: "requester", type: "address", indexed: true },
      { name: "verified", type: "bool", indexed: false },
      { name: "reason", type: "string", indexed: false },
    ],
  },
  {
    type: "event",
    name: "VerificationRevoked",
    inputs: [
      { name: "user", type: "address", indexed: true },
      { name: "reason", type: "string", indexed: false },
    ],
  },
] as const;
