// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

import "forge-std/Test.sol";
import {stdJson} from "forge-std/StdJson.sol";
import {RealDepositVerifier} from "../src/verifiers/RealDepositVerifier.sol";
import {IDepositVerifier} from "../src/interfaces/IVerifier.sol";

/// @notice Phase A — proves the deposit-binding verifier accepts a REAL groth16 proof
///         whose public `amount` matches the amount baked into `commitment`, and REJECTS
///         any note that claims a different amount. This is the CRITICAL-1 primitive:
///         a note can never be inserted claiming more R00T than was actually deposited.
///
/// Fixture (contracts/test/fixtures/deposit_proof.json) is generated by
/// scripts/gen-deposit-fixture.mjs from circuits/build/deposit/deposit_final.zkey and
/// off-chain groth16-verified before it is written.
contract DepositVerifierTest is Test {
    using stdJson for string;

    IDepositVerifier internal verifier;

    uint256[8] internal proof;
    uint256 internal binding;
    uint256 internal amount;
    uint256 internal commitment;

    function setUp() public {
        verifier = new RealDepositVerifier();

        string memory json = vm.readFile("./test/fixtures/deposit_proof.json");
        uint256[] memory p = json.readUintArray(".proof");
        require(p.length == 8, "fixture proof must be length 8");
        for (uint256 i = 0; i < 8; i++) {
            proof[i] = p[i];
        }
        binding = json.readUint(".binding");
        amount = json.readUint(".amount");
        commitment = json.readUint(".commitment");
    }

    /// matching amount -> proof valid
    function test_ValidProof_MatchingAmount() public view {
        uint256[3] memory pub = [binding, amount, commitment];
        assertTrue(verifier.verifyProof(proof, pub), "valid deposit proof must verify");
    }

    /// tampered amount (note claims more than it deposited) -> proof rejected
    function test_RejectsTamperedAmount() public view {
        uint256[3] memory pub = [binding, amount + 1, commitment];
        assertFalse(
            verifier.verifyProof(proof, pub),
            "note claiming a different amount than its commitment must be rejected"
        );
    }

    /// tampered commitment -> proof rejected (can't rebind a real amount to a fake note)
    function test_RejectsTamperedCommitment() public view {
        uint256[3] memory pub = [binding, amount, commitment + 1];
        assertFalse(
            verifier.verifyProof(proof, pub),
            "mismatched commitment must be rejected"
        );
    }

    /// tampered binding output -> proof rejected (anti-malleability)
    function test_RejectsTamperedBinding() public view {
        uint256[3] memory pub = [binding + 1, amount, commitment];
        assertFalse(
            verifier.verifyProof(proof, pub),
            "tampered public-inputs binding must be rejected"
        );
    }
}
