staging-settings:
  user-workflow:
    workflow-name: "workflow-2-defi-staging"
  workflow-artifacts:
    workflow-path: "./main.ts"
    config-path: "./config.staging.json"
    secrets-path: "../secrets.yaml"

tenderly-settings:
  user-workflow:
    workflow-name: "workflow-2-defi-tenderly"
  workflow-artifacts:
    workflow-path: "./main.ts"
    config-path: "./config.tenderly.json"
    secrets-path: "../secrets.yaml"
