/**
 * PlotMapTopo — top-down ("vertical") plan view of the Project 001 land.
 *
 * The land is divided into terrain-derived investment polygons (elevation
 * terraces + water corridor), generated by scripts/gen-zones.mjs → zones.json,
 * so every parcel is a real agronomic zone. Renders the border + contour texture
 * + river + parcels as an SVG plan; reuses PlotDetailPanel / MachinesPanel /
 * usePilotState.
 *
 * Firewall: all geometry is fuzzed/de-georeferenced (see scripts/fuzz-terrain.mjs).
 */
import { useEffect, useMemo, useRef, useState } from 'react';
import { AnimatePresence, motion } from 'framer-motion';
import { usePilotState } from './usePilotState';
import { TYPE_COLOR, eur, pct, greenLevel, parcelHeat, recentEur, regenIndex, tickerFromName, landValueR00T, fmtR00T } from './ui';
import { TYPE_LABEL, type Plot } from './types';
import { zonesToPlots, type Zone } from './data';
import { PlotDetailPanel } from './PlotDetailPanel';
import { MachinesPanel } from './MachinesPanel';

export function PlotMapTopo({ className = '' }: { className?: string }) {
  const [boundary, setBoundary] = useState<number[][] | null>(null);
  const [contours, setContours] = useState<{ l: string; p: number[][] }[]>([]);
  const [river, setRiver] = useState<number[][] | null>(null);
  const [plots, setPlots] = useState<Plot[] | null>(null);

  useEffect(() => {
    fetch('/terrain/heightmap.json').then(r => r.json()).then((d: { propertyBoundary: number[][] }) => setBoundary(d.propertyBoundary)).catch(() => {});
    fetch('/terrain/contours.json').then(r => r.json()).then((d: { contours: { l: string; p: number[][] }[] }) => setContours(d.contours || [])).catch(() => {});
    fetch('/terrain/river.json').then(r => r.json()).then((d: { centerline: number[][] }) => setRiver(d.centerline)).catch(() => {});
    fetch('/terrain/zones.json').then(r => r.json()).then((z: Zone[]) => setPlots(zonesToPlots(z))).catch(() => {});
  }, []);

  if (!boundary || !plots) {
    return <div className={`grid place-items-center aspect-[16/9] text-xs font-mono text-[var(--text-muted)] ${className}`}>dividing the land…</div>;
  }
  // key on plot ids so usePilotState re-inits if zones change
  return <LandMap key={plots.map(p => p.id).join()} className={className} initialPlots={plots} boundary={boundary} contours={contours} river={river} />;
}

function LandMap({ className = '', initialPlots, boundary, contours, river }: {
  className?: string;
  initialPlots: Plot[];
  boundary: number[][];
  contours: { l: string; p: number[][] }[];
  river: number[][] | null;
}) {
  const state = usePilotState(initialPlots);
  const { plots, machines, pending, totals } = state;
  const [selectedId, setSelectedId] = useState<string | null>(null);
  const [hoveredId, setHoveredId] = useState<string | null>(null);
  const [showMachines, setShowMachines] = useState(false);

  // ── live momentum: a clock tick + a pledge simulator so heat feels alive ──
  const [now, setNow] = useState(() => Date.now());
  useEffect(() => { const t = setInterval(() => setNow(Date.now()), 1000); return () => clearInterval(t); }, []);

  const [feed, setFeed] = useState<{ id: string; who: string; amt: number; parcel: string }[]>([]);
  const fundRef = useRef(state.fundPlot); fundRef.current = state.fundPlot;
  const plotsRef = useRef(plots); plotsRef.current = plots;
  useEffect(() => {
    const names = ['0xF3…a1', 'degen.eth', 'anon·moon', 'ser.eth', 'wagmi', 'anon·7b2', 'pleb.eth', 'apemaxi', '0x9c…d4'];
    const t = setInterval(() => {
      const open = plotsRef.current.filter(p => p.fundedEur < p.targetEur);
      if (!open.length) return;
      // bias toward already-hot parcels — momentum begets momentum
      const p = open[Math.floor(Math.random() * open.length)];
      const amt = 20 + Math.floor(Math.random() * 12) * 20;
      const who = names[Math.floor(Math.random() * names.length)];
      fundRef.current(p.id, amt, who);
      setFeed(f => [{ id: `${Date.now()}-${p.id}`, who, amt, parcel: p.name }, ...f].slice(0, 4));
    }, 3200);
    return () => clearInterval(t);
  }, []);

  const heats = plots.map(p => parcelHeat(p, now));
  const maxHeat = Math.max(1, ...heats);
  const hottestIdx = heats.indexOf(Math.max(...heats));
  const hottestId = maxHeat > 30 && hottestIdx >= 0 ? plots[hottestIdx].id : null;

  const view = useMemo(() => {
    const xs = boundary.map(p => p[0]), ys = boundary.map(p => p[1]);
    const xmin = Math.min(...xs), xmax = Math.max(...xs), ymin = Math.min(...ys), ymax = Math.max(...ys);
    const pad = 0.12 * Math.max(xmax - xmin, ymax - ymin);
    const vx0 = xmin - pad, vy0 = ymin - pad;
    const vw = (xmax - xmin) + 2 * pad, vh = (ymax - ymin) + 2 * pad;
    const S = 1000 / vw;
    const H = vh * S;
    const project = (nx: number, ny: number): [number, number] => [(nx - vx0) * S, (ny - vy0) * S];
    const inPad = (nx: number, ny: number) => nx >= vx0 && nx <= vx0 + vw && ny >= vy0 && ny <= vy0 + vh;
    return { S, H, project, inPad };
  }, [boundary]);

  const borderPath = useMemo(() =>
    boundary.map((p, i) => `${i === 0 ? 'M' : 'L'}${view.project(p[0], p[1]).map(n => n.toFixed(1)).join(' ')}`).join(' ') + ' Z',
  [boundary, view]);

  const contourPaths = useMemo(() => {
    const out: { d: string; l: string }[] = [];
    for (const c of contours) {
      if (!c.p.some(([nx, ny]) => view.inPad(nx, ny))) continue;
      out.push({ d: c.p.map((p, i) => `${i === 0 ? 'M' : 'L'}${view.project(p[0], p[1]).map(n => n.toFixed(1)).join(' ')}`).join(' '), l: c.l });
    }
    return out;
  }, [contours, view]);

  const riverPath = useMemo(() => {
    if (!river) return '';
    const pts = river.filter(([nx, ny]) => view.inPad(nx, ny));
    if (pts.length < 2) return '';
    return pts.map((p, i) => `${i === 0 ? 'M' : 'L'}${view.project(p[0], p[1]).map(n => n.toFixed(1)).join(' ')}`).join(' ');
  }, [river, view]);

  const polyPath = (poly: number[][]) => poly.map((pt, i) => `${i === 0 ? 'M' : 'L'}${view.project(pt[0], pt[1]).map(n => n.toFixed(1)).join(' ')}`).join(' ') + ' Z';

  const selected = plots.find(p => p.id === selectedId) || null;
  const hovered = plots.find(p => p.id === hoveredId) || null;
  const toPct = (sx: number, sy: number) => ({ left: `${(sx / 1000) * 100}%`, top: `${(sy / view.H) * 100}%` });

  return (
    <div className={`relative w-full ${className}`}>
      <svg viewBox={`0 0 1000 ${view.H.toFixed(1)}`} width="100%" style={{ display: 'block' }} className="select-none">
        {/* faint contour texture inside the land */}
        <g opacity={0.45}>
          {contourPaths.map((c, i) => (
            <path key={i} d={c.d} fill="none" stroke="var(--accent-on-bg)" strokeOpacity={c.l === 'major' ? 0.45 : c.l === 'medium' ? 0.26 : 0.14} strokeWidth={c.l === 'major' ? 1.1 : 0.7} strokeLinejoin="round" />
          ))}
        </g>

        {/* faint land base — hides any smoothing gaps between parcels */}
        <path d={borderPath} fill="var(--accent-on-bg)" fillOpacity={0.05} stroke="none" />

        {/* investment polygons — terrain-derived organic parcels */}
        {plots.map((p) => {
          if (!p.poly) return null;
          const color = TYPE_COLOR[p.type];
          const g = greenLevel(p.status, p.fundedEur, p.targetEur);
          const active = hoveredId === p.id || selectedId === p.id;
          const [cx, cy] = view.project(p.x, p.y);
          // screen size of the parcel → decide whether the name fits
          const sxs = p.poly.map(pt => view.project(pt[0], pt[1]));
          const w = Math.max(...sxs.map(s => s[0])) - Math.min(...sxs.map(s => s[0]));
          const h = Math.max(...sxs.map(s => s[1])) - Math.min(...sxs.map(s => s[1]));
          const showName = w > 78 && h > 30;
          const funded = p.fundedEur >= p.targetEur;
          const d = polyPath(p.poly);
          const hn = parcelHeat(p, now) / maxHeat;   // 0..1 momentum
          const isHot = p.id === hottestId;
          return (
            <g key={p.id} style={{ cursor: 'pointer' }}
               onMouseEnter={() => setHoveredId(p.id)} onMouseLeave={() => setHoveredId(h2 => h2 === p.id ? null : h2)}
               onClick={() => setSelectedId(p.id)}>
              {/* momentum glow — hot parcels pulse orange */}
              {hn > 0.14 && (
                <motion.path d={d} fill="none" stroke="#FF7A00" strokeLinejoin="round"
                  strokeWidth={4 + 5 * hn}
                  animate={{ strokeOpacity: [0.15 * hn + 0.1, 0.5 * hn + 0.15, 0.15 * hn + 0.1] }}
                  transition={{ duration: 1.6, repeat: Infinity, ease: 'easeInOut' }} />
              )}
              {/* fully-funded parcels get a solid saturated fill + glow ring;
                  still-seeking parcels stay faint & dashed */}
              {funded && <path d={d} fill="none" stroke={color} strokeWidth={5} strokeOpacity={0.18} strokeLinejoin="round" />}
              <path d={d} fill={color} fillOpacity={funded ? (0.5 * (active ? 1.15 : 1)) : (0.12 + 0.3 * g) * (active ? 1.4 : 1)}
                    stroke={color} strokeWidth={active ? 2.6 : funded ? 1.8 : 1.1}
                    strokeOpacity={funded ? 1 : p.status === 'seeking' ? 0.45 : 0.8}
                    strokeDasharray={funded ? undefined : '5 4'}
                    strokeLinejoin="round" />
              <text x={cx} y={cy + (showName ? -1 : 3)} textAnchor="middle" className="font-mono" fontSize={11} fontWeight={600} fill={color} style={{ paintOrder: 'stroke', stroke: 'var(--bg-primary)', strokeWidth: 3, strokeLinejoin: 'round' }}>
                {p.status === 'verified' ? '✅ ' : ''}{pct(p.fundedEur, p.targetEur)}%{isHot ? ' 🔥' : ''}
              </text>
              {showName && (
                <text x={cx} y={cy + 10} textAnchor="middle" className="font-mono" fontSize={7} fill="var(--text-muted)" style={{ paintOrder: 'stroke', stroke: 'var(--bg-primary)', strokeWidth: 2.5, strokeLinejoin: 'round' }}>
                  {p.name}
                </text>
              )}
            </g>
          );
        })}

        {/* land border on top */}
        <path d={borderPath} fill="none" stroke="var(--accent-on-bg)" strokeWidth={2.6} strokeLinejoin="round" strokeOpacity={0.9} />

        {/* river */}
        {riverPath && <path d={riverPath} fill="none" stroke="#5BA8B5" strokeWidth={3.2} strokeOpacity={0.6} strokeLinecap="round" strokeLinejoin="round" />}

        {/* infrastructure pins */}
        {machines.filter(m => m.x != null && m.y != null).map((m) => {
          const [sx, sy] = view.project(m.x as number, m.y as number);
          return (
            <g key={m.id} style={{ cursor: 'pointer' }} onClick={() => setShowMachines(true)} onMouseEnter={() => setHoveredId('m:' + m.id)} onMouseLeave={() => setHoveredId(h => h === 'm:' + m.id ? null : h)}>
              <circle cx={sx} cy={sy} r={9} fill="var(--bg-elevated)" stroke="#D4A84B" strokeWidth={1.4} />
              <text x={sx} y={sy + 4.5} textAnchor="middle" fontSize={9}>{m.emoji}</text>
            </g>
          );
        })}
      </svg>

      {/* hover tooltip */}
      <AnimatePresence>
        {hovered && hovered.id !== selectedId && (() => {
          const [sx, sy] = view.project(hovered.x, hovered.y);
          return (
            <motion.div key={hovered.id} initial={{ opacity: 0, y: 6 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0, y: 6 }} transition={{ duration: 0.14 }}
              className="pointer-events-none absolute z-30 w-52 -translate-x-1/2 rounded-lg border border-[var(--border)] p-3 backdrop-blur-md"
              style={{ ...toPct(sx, sy), marginTop: 10, background: 'color-mix(in srgb, var(--bg-elevated) 92%, transparent)', boxShadow: 'var(--shadow-md)' }}>
              <div className="flex items-center justify-between gap-1.5 mb-1">
                <span className="inline-flex items-center gap-1.5">
                  <span className="w-2 h-2 rounded-full" style={{ background: TYPE_COLOR[hovered.type] }} />
                  <span className="text-[9px] font-mono uppercase tracking-wide text-[var(--text-muted)]">{TYPE_LABEL[hovered.type]}</span>
                </span>
                <span className="font-mono text-[10px] font-semibold" style={{ color: TYPE_COLOR[hovered.type] }}>${tickerFromName(hovered.name)}</span>
              </div>
              <div className="flex items-center justify-between mb-1.5">
                <p className="font-display text-sm text-[var(--text-primary)] leading-tight">{hovered.name}</p>
                <span className="text-[9px] font-mono text-[var(--text-muted)]">{fmtR00T(landValueR00T(hovered))}</span>
              </div>
              <div className="h-1 rounded-full overflow-hidden mb-1.5" style={{ background: 'var(--border)' }}>
                <div className="h-full rounded-full" style={{ background: TYPE_COLOR[hovered.type], width: `${pct(hovered.fundedEur, hovered.targetEur)}%` }} />
              </div>
              <div className="flex items-center justify-between text-[10px] font-mono text-[var(--text-muted)]">
                <span>{hovered.contributions.length} backers</span>
                <span>{hovered.fundedEur >= hovered.targetEur ? 'fully backed' : `${eur(hovered.targetEur - hovered.fundedEur)} to go`}</span>
              </div>
              <div className="mt-1.5 flex items-center justify-between text-[10px] font-mono">
                <span className="text-[var(--text-muted)]">Regen Index <span className="text-[var(--accent-on-bg)] font-medium">{regenIndex(hovered, now)}</span></span>
                {recentEur(hovered, now) > 0 && <span className="text-[#FF7A00]">🔥 {eur(recentEur(hovered, now))}/min</span>}
              </div>
              <p className="mt-1.5 text-[9px] text-[var(--accent-on-bg)] font-mono">click to back →</p>
            </motion.div>
          );
        })()}
      </AnimatePresence>

      {/* legend */}
      <div className="pointer-events-none absolute right-3 top-3 z-20 flex flex-col gap-1">
        {(['syntropic', 'water', 'structure'] as const).map((t) => (
          <span key={t} className="inline-flex items-center gap-1.5 text-[9px] font-mono text-[var(--text-muted)] px-2 py-1 rounded-full backdrop-blur-sm" style={{ background: 'color-mix(in srgb, var(--bg-elevated) 70%, transparent)' }}>
            <span className="w-2 h-2 rounded-full" style={{ background: TYPE_COLOR[t] }} />{TYPE_LABEL[t]}
          </span>
        ))}
      </div>

      {/* totals HUD */}
      <div className="absolute left-3 bottom-3 z-20 flex items-center gap-3 rounded-xl border border-[var(--border)] px-3.5 py-2.5 backdrop-blur-md" style={{ background: 'color-mix(in srgb, var(--bg-elevated) 88%, transparent)' }}>
        <div>
          <p className="font-display text-base text-[var(--text-primary)] leading-none">{eur(totals.funded)}</p>
          <p className="text-[9px] font-mono text-[var(--text-muted)] mt-0.5">of {eur(totals.target)} · {totals.backers} backers · {totals.verified}/{totals.plots} verified</p>
        </div>
        <div className="w-px h-8 bg-[var(--border)]" />
        <button onClick={() => setShowMachines(true)} className="text-xs font-medium text-[var(--text-secondary)] hover:text-[var(--accent-on-bg)] transition-colors flex items-center gap-1.5">🚜 Machines & infra</button>
      </div>

      {/* live pledge feed — momentum FOMO */}
      <div className="pointer-events-none absolute right-3 bottom-3 z-20 flex flex-col-reverse gap-1.5 items-end">
        <AnimatePresence initial={false}>
          {feed.slice(0, 3).map((f) => (
            <motion.div key={f.id}
              initial={{ opacity: 0, x: 20, scale: 0.95 }} animate={{ opacity: 1, x: 0, scale: 1 }} exit={{ opacity: 0, scale: 0.9 }}
              transition={{ type: 'spring', stiffness: 320, damping: 26 }}
              className="inline-flex items-center gap-2 rounded-full border border-[var(--border)] pl-2.5 pr-3 py-1.5 backdrop-blur-md text-[11px] font-mono"
              style={{ background: 'color-mix(in srgb, var(--bg-elevated) 90%, transparent)', boxShadow: 'var(--shadow-md)' }}>
              <span>🌱</span>
              <span className="text-[var(--text-secondary)]">{f.who}</span>
              <span className="text-[var(--accent-on-bg)] font-medium">+{eur(f.amt)}</span>
              <span className="text-[var(--text-muted)] max-w-[120px] truncate">→ {f.parcel}</span>
            </motion.div>
          ))}
        </AnimatePresence>
      </div>

      {/* detail drawer */}
      <AnimatePresence>
        {selected && (
          <PlotDetailPanel plot={selected} busy={!!pending[selected.id]} verifying={!!pending[selected.id + ':verify']}
            onClose={() => setSelectedId(null)} onFund={(amt) => state.fundPlot(selected.id, amt)}
            onChooseCrop={(cid) => state.chooseCrop(selected.id, cid)} onPlant={() => state.plantPlot(selected.id)} onVerify={() => state.verifyPlot(selected.id)}
            onRename={(name) => state.renamePlot(selected.id, name)} />
        )}
      </AnimatePresence>

      {/* machines / infrastructure modal */}
      <AnimatePresence>
        {showMachines && <MachinesPanel machines={machines} pending={pending} onClose={() => setShowMachines(false)} onFund={state.fundMachine} />}
      </AnimatePresence>
    </div>
  );
}

export default PlotMapTopo;
