/**
 * PlotMapTopo — top-down ("vertical") plan view of the Project 001 land.
 *
 * The land is divided into terrain-derived investment polygons (elevation
 * terraces + water corridor), generated by scripts/gen-zones.mjs → zones.json,
 * so every parcel is a real agronomic zone. Renders the border + contour texture
 * + river + parcels as an SVG plan; reuses PlotDetailPanel / MachinesPanel /
 * usePilotState.
 *
 * Firewall: all geometry is fuzzed/de-georeferenced (see scripts/fuzz-terrain.mjs).
 */
import { useEffect, useMemo, useState } from 'react';
import { AnimatePresence, motion } from 'framer-motion';
import { usePilotState } from './usePilotState';
import { TYPE_COLOR, eur, pct, greenLevel } from './ui';
import { TYPE_LABEL, type Plot } from './types';
import { zonesToPlots, type Zone } from './data';
import { PlotDetailPanel } from './PlotDetailPanel';
import { MachinesPanel } from './MachinesPanel';

export function PlotMapTopo({ className = '' }: { className?: string }) {
  const [boundary, setBoundary] = useState<number[][] | null>(null);
  const [contours, setContours] = useState<{ l: string; p: number[][] }[]>([]);
  const [river, setRiver] = useState<number[][] | null>(null);
  const [plots, setPlots] = useState<Plot[] | null>(null);

  useEffect(() => {
    fetch('/terrain/heightmap.json').then(r => r.json()).then((d: { propertyBoundary: number[][] }) => setBoundary(d.propertyBoundary)).catch(() => {});
    fetch('/terrain/contours.json').then(r => r.json()).then((d: { contours: { l: string; p: number[][] }[] }) => setContours(d.contours || [])).catch(() => {});
    fetch('/terrain/river.json').then(r => r.json()).then((d: { centerline: number[][] }) => setRiver(d.centerline)).catch(() => {});
    fetch('/terrain/zones.json').then(r => r.json()).then((z: Zone[]) => setPlots(zonesToPlots(z))).catch(() => {});
  }, []);

  if (!boundary || !plots) {
    return <div className={`grid place-items-center aspect-[16/9] text-xs font-mono text-[var(--text-muted)] ${className}`}>dividing the land…</div>;
  }
  // key on plot ids so usePilotState re-inits if zones change
  return <LandMap key={plots.map(p => p.id).join()} className={className} initialPlots={plots} boundary={boundary} contours={contours} river={river} />;
}

function LandMap({ className = '', initialPlots, boundary, contours, river }: {
  className?: string;
  initialPlots: Plot[];
  boundary: number[][];
  contours: { l: string; p: number[][] }[];
  river: number[][] | null;
}) {
  const state = usePilotState(initialPlots);
  const { plots, machines, pending, totals } = state;
  const [selectedId, setSelectedId] = useState<string | null>(null);
  const [hoveredId, setHoveredId] = useState<string | null>(null);
  const [showMachines, setShowMachines] = useState(false);

  const view = useMemo(() => {
    const xs = boundary.map(p => p[0]), ys = boundary.map(p => p[1]);
    const xmin = Math.min(...xs), xmax = Math.max(...xs), ymin = Math.min(...ys), ymax = Math.max(...ys);
    const pad = 0.12 * Math.max(xmax - xmin, ymax - ymin);
    const vx0 = xmin - pad, vy0 = ymin - pad;
    const vw = (xmax - xmin) + 2 * pad, vh = (ymax - ymin) + 2 * pad;
    const S = 1000 / vw;
    const H = vh * S;
    const project = (nx: number, ny: number): [number, number] => [(nx - vx0) * S, (ny - vy0) * S];
    const inPad = (nx: number, ny: number) => nx >= vx0 && nx <= vx0 + vw && ny >= vy0 && ny <= vy0 + vh;
    return { S, H, project, inPad };
  }, [boundary]);

  const borderPath = useMemo(() =>
    boundary.map((p, i) => `${i === 0 ? 'M' : 'L'}${view.project(p[0], p[1]).map(n => n.toFixed(1)).join(' ')}`).join(' ') + ' Z',
  [boundary, view]);

  const contourPaths = useMemo(() => {
    const out: { d: string; l: string }[] = [];
    for (const c of contours) {
      if (!c.p.some(([nx, ny]) => view.inPad(nx, ny))) continue;
      out.push({ d: c.p.map((p, i) => `${i === 0 ? 'M' : 'L'}${view.project(p[0], p[1]).map(n => n.toFixed(1)).join(' ')}`).join(' '), l: c.l });
    }
    return out;
  }, [contours, view]);

  const riverPath = useMemo(() => {
    if (!river) return '';
    const pts = river.filter(([nx, ny]) => view.inPad(nx, ny));
    if (pts.length < 2) return '';
    return pts.map((p, i) => `${i === 0 ? 'M' : 'L'}${view.project(p[0], p[1]).map(n => n.toFixed(1)).join(' ')}`).join(' ');
  }, [river, view]);

  const polyPath = (poly: number[][]) => poly.map((pt, i) => `${i === 0 ? 'M' : 'L'}${view.project(pt[0], pt[1]).map(n => n.toFixed(1)).join(' ')}`).join(' ') + ' Z';

  const selected = plots.find(p => p.id === selectedId) || null;
  const hovered = plots.find(p => p.id === hoveredId) || null;
  const toPct = (sx: number, sy: number) => ({ left: `${(sx / 1000) * 100}%`, top: `${(sy / view.H) * 100}%` });

  return (
    <div className={`relative w-full ${className}`}>
      <svg viewBox={`0 0 1000 ${view.H.toFixed(1)}`} width="100%" style={{ display: 'block' }} className="select-none">
        {/* faint contour texture inside the land */}
        <g opacity={0.45}>
          {contourPaths.map((c, i) => (
            <path key={i} d={c.d} fill="none" stroke="var(--accent-on-bg)" strokeOpacity={c.l === 'major' ? 0.45 : c.l === 'medium' ? 0.26 : 0.14} strokeWidth={c.l === 'major' ? 1.1 : 0.7} strokeLinejoin="round" />
          ))}
        </g>

        {/* investment polygons — terrain-derived terraces + water corridor */}
        {plots.map((p) => {
          if (!p.poly) return null;
          const color = TYPE_COLOR[p.type];
          const g = greenLevel(p.status, p.fundedEur, p.targetEur);
          const active = hoveredId === p.id || selectedId === p.id;
          const [cx, cy] = view.project(p.x, p.y);
          return (
            <g key={p.id} style={{ cursor: 'pointer' }}
               onMouseEnter={() => setHoveredId(p.id)} onMouseLeave={() => setHoveredId(h => h === p.id ? null : h)}
               onClick={() => setSelectedId(p.id)}>
              <path d={polyPath(p.poly)} fill={color} fillOpacity={(0.12 + 0.34 * g) * (active ? 1.5 : 1)}
                    stroke={color} strokeWidth={active ? 2.6 : 1.3}
                    strokeOpacity={p.status === 'seeking' ? 0.55 : 0.9}
                    strokeDasharray={p.status === 'verified' ? undefined : '5 4'}
                    strokeLinejoin="round" />
              <text x={cx} y={cy - 1} textAnchor="middle" className="font-mono" fontSize={11} fontWeight={600} fill={color} style={{ paintOrder: 'stroke', stroke: 'var(--bg-primary)', strokeWidth: 3, strokeLinejoin: 'round' }}>
                {p.status === 'verified' ? '✅ ' : ''}{pct(p.fundedEur, p.targetEur)}%
              </text>
              <text x={cx} y={cy + 10} textAnchor="middle" className="font-mono" fontSize={7} fill="var(--text-muted)" style={{ paintOrder: 'stroke', stroke: 'var(--bg-primary)', strokeWidth: 2.5, strokeLinejoin: 'round' }}>
                {p.name}
              </text>
            </g>
          );
        })}

        {/* land border on top */}
        <path d={borderPath} fill="none" stroke="var(--accent-on-bg)" strokeWidth={2.6} strokeLinejoin="round" strokeOpacity={0.9} />

        {/* river */}
        {riverPath && <path d={riverPath} fill="none" stroke="#5BA8B5" strokeWidth={3.2} strokeOpacity={0.6} strokeLinecap="round" strokeLinejoin="round" />}

        {/* infrastructure pins */}
        {machines.filter(m => m.x != null && m.y != null).map((m) => {
          const [sx, sy] = view.project(m.x as number, m.y as number);
          return (
            <g key={m.id} style={{ cursor: 'pointer' }} onClick={() => setShowMachines(true)} onMouseEnter={() => setHoveredId('m:' + m.id)} onMouseLeave={() => setHoveredId(h => h === 'm:' + m.id ? null : h)}>
              <circle cx={sx} cy={sy} r={9} fill="var(--bg-elevated)" stroke="#D4A84B" strokeWidth={1.4} />
              <text x={sx} y={sy + 4.5} textAnchor="middle" fontSize={9}>{m.emoji}</text>
            </g>
          );
        })}
      </svg>

      {/* hover tooltip */}
      <AnimatePresence>
        {hovered && hovered.id !== selectedId && (() => {
          const [sx, sy] = view.project(hovered.x, hovered.y);
          return (
            <motion.div key={hovered.id} initial={{ opacity: 0, y: 6 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0, y: 6 }} transition={{ duration: 0.14 }}
              className="pointer-events-none absolute z-30 w-52 -translate-x-1/2 rounded-lg border border-[var(--border)] p-3 backdrop-blur-md"
              style={{ ...toPct(sx, sy), marginTop: 10, background: 'color-mix(in srgb, var(--bg-elevated) 92%, transparent)', boxShadow: 'var(--shadow-md)' }}>
              <div className="flex items-center gap-1.5 mb-1">
                <span className="w-2 h-2 rounded-full" style={{ background: TYPE_COLOR[hovered.type] }} />
                <span className="text-[9px] font-mono uppercase tracking-wide text-[var(--text-muted)]">{TYPE_LABEL[hovered.type]}</span>
              </div>
              <p className="font-display text-sm text-[var(--text-primary)] leading-tight mb-1.5">{hovered.name}</p>
              <div className="h-1 rounded-full overflow-hidden mb-1.5" style={{ background: 'var(--border)' }}>
                <div className="h-full rounded-full" style={{ background: TYPE_COLOR[hovered.type], width: `${pct(hovered.fundedEur, hovered.targetEur)}%` }} />
              </div>
              <div className="flex items-center justify-between text-[10px] font-mono text-[var(--text-muted)]">
                <span>{hovered.contributions.length} backers</span>
                <span>{hovered.fundedEur >= hovered.targetEur ? 'fully backed' : `${eur(hovered.targetEur - hovered.fundedEur)} to go`}</span>
              </div>
              <p className="mt-1.5 text-[9px] text-[var(--accent-on-bg)] font-mono">click to back →</p>
            </motion.div>
          );
        })()}
      </AnimatePresence>

      {/* legend */}
      <div className="pointer-events-none absolute right-3 top-3 z-20 flex flex-col gap-1">
        {(['syntropic', 'water', 'structure'] as const).map((t) => (
          <span key={t} className="inline-flex items-center gap-1.5 text-[9px] font-mono text-[var(--text-muted)] px-2 py-1 rounded-full backdrop-blur-sm" style={{ background: 'color-mix(in srgb, var(--bg-elevated) 70%, transparent)' }}>
            <span className="w-2 h-2 rounded-full" style={{ background: TYPE_COLOR[t] }} />{TYPE_LABEL[t]}
          </span>
        ))}
      </div>

      {/* totals HUD */}
      <div className="absolute left-3 bottom-3 z-20 flex items-center gap-3 rounded-xl border border-[var(--border)] px-3.5 py-2.5 backdrop-blur-md" style={{ background: 'color-mix(in srgb, var(--bg-elevated) 88%, transparent)' }}>
        <div>
          <p className="font-display text-base text-[var(--text-primary)] leading-none">{eur(totals.funded)}</p>
          <p className="text-[9px] font-mono text-[var(--text-muted)] mt-0.5">of {eur(totals.target)} · {totals.backers} backers · {totals.verified}/{totals.plots} verified</p>
        </div>
        <div className="w-px h-8 bg-[var(--border)]" />
        <button onClick={() => setShowMachines(true)} className="text-xs font-medium text-[var(--text-secondary)] hover:text-[var(--accent-on-bg)] transition-colors flex items-center gap-1.5">🚜 Machines & infra</button>
      </div>

      {/* detail drawer */}
      <AnimatePresence>
        {selected && (
          <PlotDetailPanel plot={selected} busy={!!pending[selected.id]} verifying={!!pending[selected.id + ':verify']}
            onClose={() => setSelectedId(null)} onFund={(amt) => state.fundPlot(selected.id, amt)}
            onChooseCrop={(cid) => state.chooseCrop(selected.id, cid)} onPlant={() => state.plantPlot(selected.id)} onVerify={() => state.verifyPlot(selected.id)} />
        )}
      </AnimatePresence>

      {/* machines / infrastructure modal */}
      <AnimatePresence>
        {showMachines && <MachinesPanel machines={machines} pending={pending} onClose={() => setShowMachines(false)} onFund={state.fundMachine} />}
      </AnimatePresence>
    </div>
  );
}

export default PlotMapTopo;
