/**
 * PlotMapTopo — top-down ("vertical") plan view of the Pilot Project land.
 *
 * The land is divided into terrain-derived investment polygons (elevation
 * terraces + water corridor), generated by scripts/gen-zones.mjs → zones.json,
 * so every parcel is a real agronomic zone. Renders the border + contour texture
 * + river + parcels as an SVG plan; reuses PlotDetailPanel / MachinesPanel /
 * usePilotState.
 *
 * Firewall: all geometry is fuzzed/de-georeferenced (see scripts/fuzz-terrain.mjs).
 */
import { useEffect, useMemo, useRef, useState } from 'react';
import { AnimatePresence, motion } from 'framer-motion';
import { usePilotState } from './usePilotState';
import { useLandBackend } from '../../hooks/useLandBackend';
import { useParcelFunding } from '../../hooks/useParcelFunding';
import { TYPE_COLOR, usd, pct, greenLevel, parcelHeat, recentEur, regenIndex, tickerFromName, landValueR00T, fmtR00T } from './ui';
import { TYPE_LABEL, type Plot } from './types';
import { zonesToPlots, type Zone } from './data';
import { PlotDetailPanel } from './PlotDetailPanel';
import { MachinesPanel } from './MachinesPanel';

// ── game helpers: scatter crops inside a parcel so the field visibly fills ──
function mulberry(seed: number) {
  return () => { seed |= 0; seed = (seed + 0x6D2B79F5) | 0; let t = Math.imul(seed ^ (seed >>> 15), 1 | seed); t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t; return ((t ^ (t >>> 14)) >>> 0) / 4294967296; };
}
function pointInPoly(nx: number, ny: number, poly: number[][]) {
  let inside = false;
  for (let i = 0, j = poly.length - 1; i < poly.length; j = i++) {
    const [xi, yi] = poly[i], [xj, yj] = poly[j];
    if (((yi > ny) !== (yj > ny)) && (nx < ((xj - xi) * (ny - yi)) / (yj - yi) + xi)) inside = !inside;
  }
  return inside;
}
function seedFromId(id: string) { let h = 2166136261; for (let i = 0; i < id.length; i++) h = Math.imul(h ^ id.charCodeAt(i), 16777619); return h >>> 0; }
// jittered interior sample points, up to `max`, biased away from the border
function sampleField(poly: number[][], max: number, seed: number): [number, number][] {
  const xs = poly.map(p => p[0]), ys = poly.map(p => p[1]);
  const xmin = Math.min(...xs), xmax = Math.max(...xs), ymin = Math.min(...ys), ymax = Math.max(...ys);
  const rnd = mulberry(seed);
  const pts: [number, number][] = [];
  let tries = 0;
  while (pts.length < max && tries < max * 60) {
    tries++;
    const nx = xmin + rnd() * (xmax - xmin), ny = ymin + rnd() * (ymax - ymin);
    if (pointInPoly(nx, ny, poly)) pts.push([nx, ny]);
  }
  return pts;
}
const REVIVAL_LEVELS = ['Barren', 'Sprouting', 'Greening', 'Flourishing', 'Thriving', 'Revived'];

export function PlotMapTopo({ className = '' }: { className?: string }) {
  const [boundary, setBoundary] = useState<number[][] | null>(null);
  const [contours, setContours] = useState<{ l: string; p: number[][] }[]>([]);
  const [river, setRiver] = useState<number[][] | null>(null);
  const [plots, setPlots] = useState<Plot[] | null>(null);
  const [loadErr, setLoadErr] = useState<string | null>(null);

  useEffect(() => {
    const getJson = async (url: string) => {
      const r = await fetch(url);
      if (!r.ok) throw new Error(`${url} → ${r.status}`);
      return r.json();
    };
    // boundary + plots are required to render; contours/river are optional flourish
    getJson('/terrain/heightmap.json').then((d: { propertyBoundary: number[][] }) => setBoundary(d.propertyBoundary))
      .catch((e) => { console.error('[PlotMap] boundary load failed', e); setLoadErr(String(e.message || e)); });
    getJson('/terrain/zones.json').then((z: Zone[]) => setPlots(zonesToPlots(z)))
      .catch((e) => { console.error('[PlotMap] zones load failed', e); setLoadErr(String(e.message || e)); });
    getJson('/terrain/contours.json').then((d: { contours: { l: string; p: number[][] }[] }) => setContours(d.contours || [])).catch((e) => console.warn('[PlotMap] contours', e));
    getJson('/terrain/river.json').then((d: { centerline: number[][] }) => setRiver(d.centerline)).catch((e) => console.warn('[PlotMap] river', e));
  }, []);

  if (loadErr) {
    return <div className={`grid place-items-center aspect-[16/9] text-xs font-mono text-[var(--text-muted)] gap-1 text-center px-4 ${className}`}>
      <span>couldn't load the land</span>
      <span className="text-[10px] opacity-70">{loadErr} · check console / dev server</span>
    </div>;
  }
  if (!boundary || !plots) {
    return <div className={`grid place-items-center aspect-[16/9] text-xs font-mono text-[var(--text-muted)] ${className}`}>dividing the land…</div>;
  }
  // key on plot ids so usePilotState re-inits if zones change
  return <LandMap key={plots.map(p => p.id).join()} className={className} initialPlots={plots} boundary={boundary} contours={contours} river={river} />;
}

function LandMap({ className = '', initialPlots, boundary, contours, river }: {
  className?: string;
  initialPlots: Plot[];
  boundary: number[][];
  contours: { l: string; p: number[][] }[];
  river: number[][] | null;
}) {
  // Real Land pledges when the pilot Land is deployed + wallet connected; mock otherwise.
  const { backend } = useLandBackend();
  const state = usePilotState(initialPlots, backend);
  const { plots: rawPlots, machines, pending } = state;

  // Merge REAL on-chain funding (raised/target per parcel) into the map so nothing is imagined.
  const { funding: onChainFunding } = useParcelFunding();
  const plots = useMemo(() => rawPlots.map((p) => {
    const tk = p.ticker ?? tickerFromName(p.name);
    const f = onChainFunding[tk];
    return f && f.targetUsd > 0 ? { ...p, fundedEur: f.fundedUsd, targetEur: f.targetUsd } : { ...p, fundedEur: 0 };
  }), [rawPlots, onChainFunding]);

  // Real totals from the merged plots (funded/target on-chain; backers ≈ funded parcels).
  const totals = useMemo(() => ({
    funded: plots.reduce((a, p) => a + p.fundedEur, 0),
    target: plots.reduce((a, p) => a + p.targetEur, 0),
    backers: plots.filter((p) => p.fundedEur > 0).length,
    verified: plots.filter((p) => p.targetEur > 0 && p.fundedEur >= p.targetEur).length,
    plots: plots.length,
  }), [plots]);

  // ── ALIVE, but REAL: pulse a parcel when its on-chain funding actually increases ──
  // Diff each funding poll against the previous snapshot; a real donation → celebratory ring
  // + a live-feed line. No fake timer, no imagined pledges — only real on-chain deltas.
  const prevFundedRef = useRef<Record<string, number>>({});
  const [pulseAt, setPulseAt] = useState<Record<string, number>>({}); // plot.id → ts of last real donation
  const [liveFeed, setLiveFeed] = useState<{ id: string; ticker: string; deltaUsd: number }[]>([]);
  useEffect(() => {
    const prev = prevFundedRef.current;
    const next: Record<string, number> = {};
    let firstSnapshot = Object.keys(prev).length === 0;
    for (const p of plots) {
      next[p.id] = p.fundedEur;
      const before = prev[p.id];
      if (!firstSnapshot && before != null && p.fundedEur > before + 1e-9) {
        const delta = p.fundedEur - before;
        setPulseAt((s) => ({ ...s, [p.id]: Date.now() }));
        const tk = p.ticker ?? tickerFromName(p.name);
        setLiveFeed((f) => [{ id: `${Date.now()}-${p.id}`, ticker: tk, deltaUsd: delta }, ...f].slice(0, 3));
        setTimeout(() => setPulseAt((s) => { const c = { ...s }; delete c[p.id]; return c; }), 3200);
      }
    }
    prevFundedRef.current = next;
  }, [plots]);
  const [selectedId, setSelectedId] = useState<string | null>(null);
  const [hoveredId, setHoveredId] = useState<string | null>(null);
  const [showMachines, setShowMachines] = useState(false);

  // ── heat is computed once at mount ──
  // The old timer-driven `now` re-rendered the ENTIRE map SVG on an interval, which read as
  // a flicker/hydration glitch. Funding %s update from the on-chain poll (useParcelFunding),
  // not a clock, so there's no need to tick `now` — freeze it and the churn disappears.
  const [now] = useState(() => Date.now());
  // (simulated pledge feed removed — the live feed + parcel pulses are driven by REAL
  //  on-chain funding deltas from useParcelFunding, see the pulse effect above.)

  const heats = plots.map(p => parcelHeat(p, now));
  const maxHeat = Math.max(1, ...heats);
  const hottestIdx = heats.indexOf(Math.max(...heats));
  const hottestId = maxHeat > 30 && hottestIdx >= 0 ? plots[hottestIdx].id : null;

  const view = useMemo(() => {
    const xs = boundary.map(p => p[0]), ys = boundary.map(p => p[1]);
    const xmin = Math.min(...xs), xmax = Math.max(...xs), ymin = Math.min(...ys), ymax = Math.max(...ys);
    const pad = 0.12 * Math.max(xmax - xmin, ymax - ymin);
    const vx0 = xmin - pad, vy0 = ymin - pad;
    const vw = (xmax - xmin) + 2 * pad, vh = (ymax - ymin) + 2 * pad;
    const S = 1000 / vw;
    const H = vh * S;
    const project = (nx: number, ny: number): [number, number] => [(nx - vx0) * S, (ny - vy0) * S];
    const inPad = (nx: number, ny: number) => nx >= vx0 && nx <= vx0 + vw && ny >= vy0 && ny <= vy0 + vh;
    return { S, H, project, inPad };
  }, [boundary]);

  const borderPath = useMemo(() =>
    boundary.map((p, i) => `${i === 0 ? 'M' : 'L'}${view.project(p[0], p[1]).map(n => n.toFixed(1)).join(' ')}`).join(' ') + ' Z',
  [boundary, view]);

  const contourPaths = useMemo(() => {
    const out: { d: string; l: string }[] = [];
    for (const c of contours) {
      if (!c.p.some(([nx, ny]) => view.inPad(nx, ny))) continue;
      out.push({ d: c.p.map((p, i) => `${i === 0 ? 'M' : 'L'}${view.project(p[0], p[1]).map(n => n.toFixed(1)).join(' ')}`).join(' '), l: c.l });
    }
    return out;
  }, [contours, view]);

  const riverPath = useMemo(() => {
    if (!river) return '';
    const pts = river.filter(([nx, ny]) => view.inPad(nx, ny));
    if (pts.length < 2) return '';
    return pts.map((p, i) => `${i === 0 ? 'M' : 'L'}${view.project(p[0], p[1]).map(n => n.toFixed(1)).join(' ')}`).join(' ');
  }, [river, view]);

  const polyPath = (poly: number[][]) => poly.map((pt, i) => `${i === 0 ? 'M' : 'L'}${view.project(pt[0], pt[1]).map(n => n.toFixed(1)).join(' ')}`).join(' ') + ' Z';

  // crop scatter per parcel (deterministic; slots fill as funding grows)
  const cropField = useMemo(() => {
    const out: Record<string, { pts: [number, number][]; max: number }> = {};
    for (const p of plots) {
      if (!p.poly) continue;
      const max = Math.max(3, Math.min(18, Math.round((p.areaHa ?? 0.5) * 7)));
      out[p.id] = { pts: sampleField(p.poly, max, seedFromId(p.id)), max };
    }
    return out;
  }, [plots]);

  // overall land revival (parcels + infra funded / goal)
  const revivalPct = Math.min(100, Math.round((totals.funded / Math.max(1, totals.target)) * 100));
  const revivalLevel = Math.min(REVIVAL_LEVELS.length - 1, Math.floor(revivalPct / 20));

  const selected = plots.find(p => p.id === selectedId) || null;
  const hovered = plots.find(p => p.id === hoveredId) || null;
  const toPct = (sx: number, sy: number) => ({ left: `${(sx / 1000) * 100}%`, top: `${(sy / view.H) * 100}%` });

  return (
    <div className={`relative w-full ${className}`}>
      <svg viewBox={`0 0 1000 ${view.H.toFixed(1)}`} width="100%" style={{ display: 'block' }} className="select-none">
        {/* faint contour texture inside the land */}
        <g opacity={0.45}>
          {contourPaths.map((c, i) => (
            <path key={i} d={c.d} fill="none" stroke="var(--accent-on-bg)" strokeOpacity={c.l === 'major' ? 0.45 : c.l === 'medium' ? 0.26 : 0.14} strokeWidth={c.l === 'major' ? 1.1 : 0.7} strokeLinejoin="round" />
          ))}
        </g>

        {/* faint land base — hides any smoothing gaps between parcels */}
        <path d={borderPath} fill="var(--accent-on-bg)" fillOpacity={0.05} stroke="none" />

        {/* investment polygons — terrain-derived organic parcels */}
        {plots.map((p) => {
          if (!p.poly) return null;
          const color = TYPE_COLOR[p.type];
          const g = greenLevel(p.status, p.fundedEur, p.targetEur);
          const active = hoveredId === p.id || selectedId === p.id;
          const [cx, cy] = view.project(p.x, p.y);
          // screen size of the parcel → decide whether the name fits
          const sxs = p.poly.map(pt => view.project(pt[0], pt[1]));
          const w = Math.max(...sxs.map(s => s[0])) - Math.min(...sxs.map(s => s[0]));
          const h = Math.max(...sxs.map(s => s[1])) - Math.min(...sxs.map(s => s[1]));
          const showName = w > 70 && h > 34;
          const funded = p.fundedEur >= p.targetEur;
          const d = polyPath(p.poly);
          const hn = parcelHeat(p, now) / maxHeat;   // 0..1 momentum
          const isHot = p.id === hottestId;
          const areaTxt = p.areaHa != null ? `${p.areaHa.toFixed(2)} ha` : '';
          return (
            <g key={p.id} style={{ cursor: 'pointer' }}
               onMouseEnter={() => setHoveredId(p.id)} onMouseLeave={() => setHoveredId(h2 => h2 === p.id ? null : h2)}
               onClick={() => setSelectedId(p.id)}>
              {/* momentum glow — hot parcels pulse orange */}
              {hn > 0.14 && (
                <motion.path d={d} fill="none" stroke="#FF7A00" strokeLinejoin="round"
                  strokeWidth={4 + 5 * hn}
                  animate={{ strokeOpacity: [0.15 * hn + 0.1, 0.5 * hn + 0.15, 0.15 * hn + 0.1] }}
                  transition={{ duration: 1.6, repeat: Infinity, ease: 'easeInOut' }} />
              )}
              {/* REAL donation pulse — fires once when this parcel's on-chain funding increases */}
              {pulseAt[p.id] && (
                <motion.path key={pulseAt[p.id]} d={d} fill="none" stroke={color} strokeLinejoin="round"
                  initial={{ strokeOpacity: 0.9, strokeWidth: 2 }}
                  animate={{ strokeOpacity: 0, strokeWidth: 16 }}
                  transition={{ duration: 1.4, ease: 'easeOut' }} />
              )}
              {/* fully-funded parcels get a solid saturated fill + glow ring;
                  still-seeking parcels stay faint & dashed */}
              {funded && <path d={d} fill="none" stroke={color} strokeWidth={5} strokeOpacity={0.18} strokeLinejoin="round" />}
              <path d={d} fill={color} fillOpacity={funded ? (0.5 * (active ? 1.15 : 1)) : (0.12 + 0.3 * g) * (active ? 1.4 : 1)}
                    stroke={color} strokeWidth={active ? 2.6 : funded ? 1.8 : 1.1}
                    strokeOpacity={funded ? 1 : p.status === 'seeking' ? 0.45 : 0.8}
                    strokeDasharray={funded ? undefined : '5 4'}
                    strokeLinejoin="round" />
              {/* crops fill the field as it funds — the game layer */}
              {(() => {
                const field = cropField[p.id];
                if (!field) return null;
                const frac = Math.min(1, p.fundedEur / Math.max(1, p.targetEur));
                const grown = Math.max(1, Math.round(field.max * frac));
                const sizeByStatus = p.status === 'verified' ? 15 : p.status === 'planted' ? 13 : p.status === 'funded' ? 12 : p.status === 'greening' ? 11 : 10;
                return field.pts.slice(0, grown).map((pt, k) => {
                  const [sx, sy] = view.project(pt[0], pt[1]);
                  return <text key={k} x={sx} y={sy} textAnchor="middle" fontSize={sizeByStatus} opacity={0.9} style={{ pointerEvents: 'none' }}>{p.emoji}</text>;
                });
              })()}
              {/* label pill: $TICKER · % (+🔥) */}
              <rect x={cx - 30} y={cy - 8} width={60} height={16} rx={8} fill="var(--bg-primary)" opacity={0.72} />
              <text x={cx} y={cy + 3.5} textAnchor="middle" className="font-mono" fontSize={10} fontWeight={700} fill={color}>
                {p.status === 'verified' ? '✅' : ''}${p.ticker ?? tickerFromName(p.name)} {pct(p.fundedEur, p.targetEur)}%{isHot ? '🔥' : ''}
              </text>
              {showName && (
                <text x={cx} y={cy + 17} textAnchor="middle" className="font-mono" fontSize={7.5} fill="var(--text-muted)" style={{ paintOrder: 'stroke', stroke: 'var(--bg-primary)', strokeWidth: 2.5, strokeLinejoin: 'round' }}>
                  {p.name} · {areaTxt}
                </text>
              )}
            </g>
          );
        })}

        {/* land border on top */}
        <path d={borderPath} fill="none" stroke="var(--accent-on-bg)" strokeWidth={2.6} strokeLinejoin="round" strokeOpacity={0.9} />

        {/* river */}
        {riverPath && <path d={riverPath} fill="none" stroke="#5BA8B5" strokeWidth={3.2} strokeOpacity={0.6} strokeLinecap="round" strokeLinejoin="round" />}

        {/* infrastructure pins */}
        {machines.filter(m => m.x != null && m.y != null).map((m) => {
          const [sx, sy] = view.project(m.x as number, m.y as number);
          return (
            <g key={m.id} style={{ cursor: 'pointer' }} onClick={() => setShowMachines(true)} onMouseEnter={() => setHoveredId('m:' + m.id)} onMouseLeave={() => setHoveredId(h => h === 'm:' + m.id ? null : h)}>
              <circle cx={sx} cy={sy} r={9} fill="var(--bg-elevated)" stroke="#D4A84B" strokeWidth={1.4} />
              <text x={sx} y={sy + 4.5} textAnchor="middle" fontSize={9}>{m.emoji}</text>
            </g>
          );
        })}
      </svg>

      {/* hover tooltip */}
      <AnimatePresence>
        {hovered && hovered.id !== selectedId && (() => {
          const [sx, sy] = view.project(hovered.x, hovered.y);
          return (
            <motion.div key={hovered.id} initial={{ opacity: 0, y: 6 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0, y: 6 }} transition={{ duration: 0.14 }}
              className="pointer-events-none absolute z-30 w-52 -translate-x-1/2 rounded-lg border border-[var(--border)] p-3 backdrop-blur-md"
              style={{ ...toPct(sx, sy), marginTop: 10, background: 'color-mix(in srgb, var(--bg-elevated) 92%, transparent)', boxShadow: 'var(--shadow-md)' }}>
              <div className="flex items-center justify-between gap-1.5 mb-1">
                <span className="inline-flex items-center gap-1.5">
                  <span className="w-2 h-2 rounded-full" style={{ background: TYPE_COLOR[hovered.type] }} />
                  <span className="text-[9px] font-mono uppercase tracking-wide text-[var(--text-muted)]">{TYPE_LABEL[hovered.type]}</span>
                </span>
                <span className="font-mono text-[10px] font-semibold" style={{ color: TYPE_COLOR[hovered.type] }}>${hovered.ticker ?? tickerFromName(hovered.name)}</span>
              </div>
              <div className="flex items-center justify-between mb-1">
                <p className="font-display text-sm text-[var(--text-primary)] leading-tight">{hovered.emoji} {hovered.name}</p>
                {hovered.areaHa != null && <span className="text-[9px] font-mono text-[var(--text-muted)]">{hovered.areaHa.toFixed(2)} ha</span>}
              </div>
              <div className="flex items-center justify-between mb-1.5 text-[9px] font-mono text-[var(--text-muted)]">
                <span>Land value</span><span>{fmtR00T(landValueR00T(hovered))}</span>
              </div>
              <div className="h-1 rounded-full overflow-hidden mb-1.5" style={{ background: 'var(--border)' }}>
                <div className="h-full rounded-full" style={{ background: TYPE_COLOR[hovered.type], width: `${pct(hovered.fundedEur, hovered.targetEur)}%` }} />
              </div>
              <div className="flex items-center justify-between text-[10px] font-mono text-[var(--text-muted)]">
                <span>{hovered.contributions.length} backers</span>
                <span>{hovered.fundedEur >= hovered.targetEur ? 'fully backed' : `${usd(hovered.targetEur - hovered.fundedEur)} to go`}</span>
              </div>
              <div className="mt-1.5 flex items-center justify-between text-[10px] font-mono">
                <span className="text-[var(--text-muted)]">Regen Index <span className="text-[var(--accent-on-bg)] font-medium">{regenIndex(hovered, now)}</span></span>
                {recentEur(hovered, now) > 0 && <span className="text-[#FF7A00]">🔥 {usd(recentEur(hovered, now))}/min</span>}
              </div>
              <p className="mt-1.5 text-[9px] text-[var(--accent-on-bg)] font-mono">click to back →</p>
            </motion.div>
          );
        })()}
      </AnimatePresence>

      {/* legend */}
      <div className="pointer-events-none absolute right-3 top-3 z-20 flex flex-col gap-1">
        {(['syntropic', 'water', 'structure'] as const).map((t) => (
          <span key={t} className="inline-flex items-center gap-1.5 text-[9px] font-mono text-[var(--text-muted)] px-2 py-1 rounded-full backdrop-blur-sm" style={{ background: 'color-mix(in srgb, var(--bg-elevated) 70%, transparent)' }}>
            <span className="w-2 h-2 rounded-full" style={{ background: TYPE_COLOR[t] }} />{TYPE_LABEL[t]}
          </span>
        ))}
      </div>

      {/* land-revival HUD — game meter */}
      <div className="absolute left-3 bottom-3 z-20 rounded-xl border border-[var(--border)] px-3.5 py-2.5 backdrop-blur-md w-[260px]" style={{ background: 'color-mix(in srgb, var(--bg-elevated) 90%, transparent)' }}>
        <div className="flex items-center justify-between mb-1.5">
          <span className="text-[10px] font-mono uppercase tracking-[0.12em] text-[var(--text-muted)]">🌱 Land revival</span>
          <span className="text-[10px] font-mono font-semibold text-[var(--accent-on-bg)]">LVL {revivalLevel + 1} · {REVIVAL_LEVELS[revivalLevel]}</span>
        </div>
        <div className="h-2 rounded-full overflow-hidden mb-1.5" style={{ background: 'var(--border)' }}>
          <motion.div className="h-full rounded-full" style={{ background: 'linear-gradient(90deg, var(--accent-on-bg), var(--accent))' }} animate={{ width: `${revivalPct}%` }} transition={{ duration: 0.6 }} />
        </div>
        <div className="flex items-center justify-between">
          <p className="text-[11px] font-mono text-[var(--text-secondary)]"><span className="font-semibold text-[var(--text-primary)]">{usd(totals.funded)}</span> / {usd(totals.target)}</p>
          <button onClick={() => setShowMachines(true)} className="text-[11px] font-medium text-[var(--text-secondary)] hover:text-[var(--accent-on-bg)] transition-colors">🚜 Machines</button>
        </div>
        <p className="text-[9px] font-mono text-[var(--text-muted)] mt-1">{totals.backers} backers · {totals.verified}/{totals.plots} verified · {revivalPct}% revived</p>
      </div>

      {/* live feed — REAL on-chain donations only (anonymous; we only know the amount + parcel) */}
      <div className="pointer-events-none absolute right-3 bottom-3 z-20 flex flex-col-reverse gap-1.5 items-end">
        <AnimatePresence initial={false}>
          {liveFeed.map((f) => (
            <motion.div key={f.id}
              initial={{ opacity: 0, x: 20, scale: 0.95 }} animate={{ opacity: 1, x: 0, scale: 1 }} exit={{ opacity: 0, scale: 0.9 }}
              transition={{ type: 'spring', stiffness: 320, damping: 26 }}
              className="inline-flex items-center gap-2 rounded-full border border-[var(--border)] pl-2.5 pr-3 py-1.5 backdrop-blur-md text-[11px] font-mono"
              style={{ background: 'color-mix(in srgb, var(--bg-elevated) 90%, transparent)', boxShadow: 'var(--shadow-md)' }}>
              <span>🌱</span>
              <span className="text-[var(--text-secondary)]">anon patron</span>
              <span className="text-[var(--accent-on-bg)] font-medium">+{usd(f.deltaUsd)}</span>
              <span className="text-[var(--text-muted)] max-w-[120px] truncate">→ ${f.ticker}</span>
            </motion.div>
          ))}
        </AnimatePresence>
      </div>

      {/* detail drawer */}
      <AnimatePresence>
        {selected && (
          <PlotDetailPanel plot={selected} busy={!!pending[selected.id]} verifying={!!pending[selected.id + ':verify']}
            onClose={() => setSelectedId(null)}
            onChooseCrop={(cid) => state.chooseCrop(selected.id, cid)} onPlant={() => state.plantPlot(selected.id)} onVerify={() => state.verifyPlot(selected.id)}
            onRename={(name) => state.renamePlot(selected.id, name)} />
        )}
      </AnimatePresence>

      {/* machines / infrastructure modal */}
      <AnimatePresence>
        {showMachines && <MachinesPanel machines={machines} pending={pending} onClose={() => setShowMachines(false)} onFund={state.fundMachine} />}
      </AnimatePresence>
    </div>
  );
}

export default PlotMapTopo;
